
databases:
    Testing:
      type: "mysql"
      setup:
        port: "3306"
        host: "localhost"
        user: "root"
        password: process.env.Testing
        database: "houseCup"
    Production:
      type: "mysql"
      setup:
        port: "3306"
        host: "sh4ob67ph9l80v61.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"
        user: "frqa2f0fz54ztvo5"
        password: process.env.Production
        database: "jkosy6iyv3320n7a"
models:
    Students:
      files: false
    #   db: "Testing"
      db: "Production"
      data:
        studentName:
          dataType: "string"
          required: "yes"
          encrypted: "no"
        teamName:
          dataType: "string"
          required: "yes"
          encrypted: "no"
        pointsEarned:
          dataType: "number"
          required: "yes"
          encrypted: "no"


